export type State = {
  name: string;
  slug: string;
  abbreviation: string;
  onlineAllowed: boolean;
  courtNotes: string;
  approvedSchoolCount: number;
  averagePrice: number;
  description: string;
  eligibilityNotes: string;
  certificateNotes: string;
  neighboringStates: string[];
};

export const states: State[] = [
  { name: "Alabama", slug: "alabama", abbreviation: "AL", onlineAllowed: true, courtNotes: "Most Alabama courts accept online traffic school for eligible violations.", approvedSchoolCount: 3, averagePrice: 24.99, description: "Alabama allows eligible drivers to attend online traffic school to dismiss a traffic ticket or reduce points on their driving record.", eligibilityNotes: "Eligible for one dismissal every 12 months. Must not involve DUI or reckless driving.", certificateNotes: "Submit your completion certificate to the court before your deadline.", neighboringStates: ["tennessee", "georgia", "florida", "mississippi"] },
  { name: "Alaska", slug: "alaska", abbreviation: "AK", onlineAllowed: true, courtNotes: "Alaska courts generally accept state-approved online defensive driving courses.", approvedSchoolCount: 2, averagePrice: 27.99, description: "Alaska drivers may take an approved online traffic school course to reduce points from eligible traffic violations.", eligibilityNotes: "Check with your local court for eligibility. Generally available for minor moving violations.", certificateNotes: "Electronic certificates accepted by most courts.", neighboringStates: [] },
  { name: "Arizona", slug: "arizona", abbreviation: "AZ", onlineAllowed: true, courtNotes: "Arizona has a well-established defensive driving school program accepted by all courts.", approvedSchoolCount: 5, averagePrice: 22.95, description: "Arizona's defensive driving school program is one of the most popular in the country, allowing eligible drivers to dismiss tickets completely.", eligibilityNotes: "Available once every 24 months. Must not be a criminal traffic offense. Speed must not exceed 20 mph over the limit.", certificateNotes: "Course provider submits certificate directly to the court.", neighboringStates: ["utah", "colorado", "new-mexico", "nevada", "california"] },
  { name: "Arkansas", slug: "arkansas", abbreviation: "AR", onlineAllowed: true, courtNotes: "Many Arkansas courts accept online defensive driving for point reduction.", approvedSchoolCount: 3, averagePrice: 24.99, description: "Arkansas drivers can take online traffic school to potentially reduce points on their driving record.", eligibilityNotes: "Eligibility varies by court. Contact your local court for specific requirements.", certificateNotes: "Submit certificate to your local court clerk.", neighboringStates: ["missouri", "tennessee", "mississippi", "louisiana", "texas", "oklahoma"] },
  { name: "California", slug: "california", abbreviation: "CA", onlineAllowed: true, courtNotes: "California DMV licenses online traffic schools. All listed schools are DMV-approved.", approvedSchoolCount: 5, averagePrice: 19.95, description: "California has the largest traffic school market in the US. DMV-licensed online schools can help you mask one point on your record.", eligibilityNotes: "Available once every 18 months. Must have a valid CA license. Violation must be a moving violation with a point value of 1.", certificateNotes: "School electronically submits your certificate to the DMV. No action needed from you.", neighboringStates: ["oregon", "nevada", "arizona"] },
  { name: "Colorado", slug: "colorado", abbreviation: "CO", onlineAllowed: true, courtNotes: "Colorado courts may allow online traffic school at the judge's discretion.", approvedSchoolCount: 4, averagePrice: 24.99, description: "Colorado drivers may be eligible for online traffic school depending on the court and violation type.", eligibilityNotes: "At judge's discretion. Contact the court listed on your ticket for approval before enrolling.", certificateNotes: "Submit certificate to the court by your specified deadline.", neighboringStates: ["wyoming", "nebraska", "kansas", "oklahoma", "new-mexico", "utah"] },
  { name: "Connecticut", slug: "connecticut", abbreviation: "CT", onlineAllowed: true, courtNotes: "Connecticut offers an online safe driving program for eligible drivers.", approvedSchoolCount: 3, averagePrice: 26.99, description: "Connecticut's safe driving program allows eligible drivers to potentially reduce points through an online course.", eligibilityNotes: "Available for eligible moving violations. Contact your court for specifics.", certificateNotes: "Electronic submission available for most courts.", neighboringStates: ["new-york", "massachusetts", "rhode-island"] },
  { name: "Delaware", slug: "delaware", abbreviation: "DE", onlineAllowed: true, courtNotes: "Delaware courts accept approved online defensive driving courses.", approvedSchoolCount: 3, averagePrice: 25.99, description: "Delaware drivers can take an approved online defensive driving course to reduce points on their record.", eligibilityNotes: "Generally available for minor traffic violations. Check with the court on your citation.", certificateNotes: "Submit certificate to the Delaware DMV.", neighboringStates: ["maryland", "pennsylvania", "new-jersey"] },
  { name: "Florida", slug: "florida", abbreviation: "FL", onlineAllowed: true, courtNotes: "Florida has a robust online traffic school system. All listed schools are DHSMV-approved.", approvedSchoolCount: 5, averagePrice: 19.95, description: "Florida is one of the best states for online traffic school, with numerous DHSMV-approved courses and straightforward enrollment.", eligibilityNotes: "Available up to 5 times in your lifetime (with increasing restrictions). Must elect traffic school before your court date.", certificateNotes: "School electronically submits to the clerk of court. Points are withheld from your record.", neighboringStates: ["georgia", "alabama"] },
  { name: "Georgia", slug: "georgia", abbreviation: "GA", onlineAllowed: true, courtNotes: "Georgia courts may allow online defensive driving at the judge's discretion.", approvedSchoolCount: 4, averagePrice: 24.99, description: "Georgia drivers may attend an online defensive driving course to reduce points, subject to court approval.", eligibilityNotes: "Judge's discretion. Best to request traffic school option at your court hearing or contact the court before your date.", certificateNotes: "Submit certificate to the court and Georgia DDS.", neighboringStates: ["tennessee", "north-carolina", "south-carolina", "florida", "alabama"] },
  { name: "Hawaii", slug: "hawaii", abbreviation: "HI", onlineAllowed: true, courtNotes: "Hawaii allows online traffic school for eligible violations in most districts.", approvedSchoolCount: 2, averagePrice: 29.99, description: "Hawaii drivers can take online traffic school to address eligible traffic violations.", eligibilityNotes: "Limited availability. Contact your local district court for eligibility.", certificateNotes: "Submit certificate to the court before your deadline.", neighboringStates: [] },
  { name: "Idaho", slug: "idaho", abbreviation: "ID", onlineAllowed: true, courtNotes: "Idaho courts may accept online defensive driving at the judge's discretion.", approvedSchoolCount: 3, averagePrice: 25.99, description: "Idaho drivers may be eligible for online traffic school to reduce or dismiss points from a traffic violation.", eligibilityNotes: "Court approval required. Contact the court on your ticket before enrolling.", certificateNotes: "Submit certificate to the Idaho Transportation Department and the court.", neighboringStates: ["montana", "wyoming", "utah", "nevada", "oregon", "washington"] },
  { name: "Illinois", slug: "illinois", abbreviation: "IL", onlineAllowed: true, courtNotes: "Illinois offers court-supervised online traffic safety school in many counties.", approvedSchoolCount: 4, averagePrice: 24.99, description: "Illinois drivers can attend online traffic safety school as part of court supervision to keep violations off their record.", eligibilityNotes: "Usually available for first-time or infrequent offenders. The court places you on supervision.", certificateNotes: "Certificate is submitted to the court as part of your supervision requirements.", neighboringStates: ["wisconsin", "iowa", "missouri", "kentucky", "indiana"] },
  { name: "Indiana", slug: "indiana", abbreviation: "IN", onlineAllowed: true, courtNotes: "Indiana courts may offer online defensive driving as a sentencing option.", approvedSchoolCount: 3, averagePrice: 24.99, description: "Indiana drivers may be directed to take an online defensive driving course as part of their court proceedings.", eligibilityNotes: "At judge's discretion. Usually available for minor violations.", certificateNotes: "Submit certificate to the court clerk before your deadline.", neighboringStates: ["michigan", "ohio", "kentucky", "illinois"] },
  { name: "Iowa", slug: "iowa", abbreviation: "IA", onlineAllowed: true, courtNotes: "Iowa courts may accept online defensive driving for eligible violations.", approvedSchoolCount: 3, averagePrice: 25.99, description: "Iowa drivers may take online traffic school to reduce the impact of a traffic violation on their record.", eligibilityNotes: "Court approval typically required. Contact the court listed on your citation.", certificateNotes: "Submit certificate to the Iowa DOT and the court.", neighboringStates: ["minnesota", "wisconsin", "illinois", "missouri", "nebraska", "south-dakota"] },
  { name: "Kansas", slug: "kansas", abbreviation: "KS", onlineAllowed: true, courtNotes: "Kansas courts may allow online defensive driving for point reduction.", approvedSchoolCount: 3, averagePrice: 24.99, description: "Kansas drivers may be eligible for online traffic school to reduce points on their driving record.", eligibilityNotes: "Check with your municipal or district court for eligibility requirements.", certificateNotes: "Submit certificate to the court and Kansas DMV.", neighboringStates: ["nebraska", "missouri", "oklahoma", "colorado"] },
  { name: "Kentucky", slug: "kentucky", abbreviation: "KY", onlineAllowed: true, courtNotes: "Kentucky offers a state-approved online traffic school program.", approvedSchoolCount: 3, averagePrice: 24.99, description: "Kentucky drivers can complete an approved online traffic school to reduce points on their driving record.", eligibilityNotes: "Available once every 12 months. Must be approved by the court.", certificateNotes: "Certificate is reported to the Kentucky Transportation Cabinet.", neighboringStates: ["indiana", "ohio", "west-virginia", "virginia", "tennessee", "missouri", "illinois"] },
  { name: "Louisiana", slug: "louisiana", abbreviation: "LA", onlineAllowed: true, courtNotes: "Louisiana courts accept approved online defensive driving courses.", approvedSchoolCount: 3, averagePrice: 25.99, description: "Louisiana drivers can take an approved online defensive driving course to reduce points from an eligible violation.", eligibilityNotes: "Available once every 12 months. Not available for violations in school zones or DUI.", certificateNotes: "Submit certificate to the court and Louisiana OMV.", neighboringStates: ["arkansas", "mississippi", "texas"] },
  { name: "Maine", slug: "maine", abbreviation: "ME", onlineAllowed: true, courtNotes: "Maine offers an online driver improvement program for eligible drivers.", approvedSchoolCount: 2, averagePrice: 27.99, description: "Maine drivers may take an online driver improvement course to potentially reduce points.", eligibilityNotes: "Contact the Maine BMV or your court for eligibility.", certificateNotes: "Submit certificate to the Maine BMV.", neighboringStates: ["new-hampshire"] },
  { name: "Maryland", slug: "maryland", abbreviation: "MD", onlineAllowed: true, courtNotes: "Maryland courts accept approved online driver improvement programs.", approvedSchoolCount: 4, averagePrice: 24.99, description: "Maryland drivers can attend an approved online driver improvement program to reduce points on their record.", eligibilityNotes: "Available for drivers who have accumulated points. May be required by the MVA.", certificateNotes: "Certificate is submitted to the Maryland MVA.", neighboringStates: ["pennsylvania", "delaware", "virginia", "west-virginia"] },
  { name: "Massachusetts", slug: "massachusetts", abbreviation: "MA", onlineAllowed: true, courtNotes: "Massachusetts offers an online National Safety Council defensive driving course option.", approvedSchoolCount: 3, averagePrice: 29.99, description: "Massachusetts drivers can take an approved online defensive driving course for potential insurance premium reductions.", eligibilityNotes: "Available to all licensed Massachusetts drivers. May reduce insurance surcharges.", certificateNotes: "Submit certificate to your insurance company for potential discount.", neighboringStates: ["new-hampshire", "vermont", "new-york", "connecticut", "rhode-island"] },
  { name: "Michigan", slug: "michigan", abbreviation: "MI", onlineAllowed: true, courtNotes: "Michigan courts may allow online traffic school at the judge's discretion.", approvedSchoolCount: 3, averagePrice: 24.99, description: "Michigan drivers may attend online traffic school to address eligible violations at the court's discretion.", eligibilityNotes: "Judge's discretion. Best to contact the court before enrolling.", certificateNotes: "Submit certificate to the court.", neighboringStates: ["ohio", "indiana", "wisconsin"] },
  { name: "Minnesota", slug: "minnesota", abbreviation: "MN", onlineAllowed: true, courtNotes: "Minnesota allows approved online defensive driving for eligible violations.", approvedSchoolCount: 3, averagePrice: 25.99, description: "Minnesota drivers can take an approved online defensive driving course to reduce a moving violation on their record.", eligibilityNotes: "Available once every 12 months for eligible moving violations.", certificateNotes: "Submit certificate to the Minnesota DVS.", neighboringStates: ["wisconsin", "iowa", "south-dakota", "north-dakota"] },
  { name: "Mississippi", slug: "mississippi", abbreviation: "MS", onlineAllowed: true, courtNotes: "Mississippi courts may accept online defensive driving for eligible violations.", approvedSchoolCount: 3, averagePrice: 24.99, description: "Mississippi drivers may be eligible for online traffic school to dismiss a ticket or reduce points.", eligibilityNotes: "Contact the court on your ticket for eligibility. Generally available for minor violations.", certificateNotes: "Submit certificate to the court clerk.", neighboringStates: ["tennessee", "alabama", "louisiana", "arkansas"] },
  { name: "Missouri", slug: "missouri", abbreviation: "MO", onlineAllowed: true, courtNotes: "Missouri courts widely accept online traffic school for eligible violations.", approvedSchoolCount: 4, averagePrice: 24.99, description: "Missouri drivers have good access to online traffic school options for dismissing tickets or reducing points.", eligibilityNotes: "Available for most minor moving violations. Contact your municipal court for details.", certificateNotes: "Submit certificate to the court to complete the process.", neighboringStates: ["iowa", "illinois", "kentucky", "tennessee", "arkansas", "oklahoma", "kansas", "nebraska"] },
  { name: "Montana", slug: "montana", abbreviation: "MT", onlineAllowed: true, courtNotes: "Montana courts may accept online defensive driving in some jurisdictions.", approvedSchoolCount: 2, averagePrice: 27.99, description: "Montana drivers may take online defensive driving to address traffic violations in participating courts.", eligibilityNotes: "Limited availability. Contact your court for eligibility.", certificateNotes: "Submit certificate to the court.", neighboringStates: ["north-dakota", "south-dakota", "wyoming", "idaho"] },
  { name: "Nebraska", slug: "nebraska", abbreviation: "NE", onlineAllowed: true, courtNotes: "Nebraska courts may allow online defensive driving for point reduction.", approvedSchoolCount: 3, averagePrice: 25.99, description: "Nebraska drivers may be eligible for online traffic school to reduce points on their driving record.", eligibilityNotes: "Court approval generally required. Contact the court on your citation.", certificateNotes: "Submit certificate to the Nebraska DMV and the court.", neighboringStates: ["south-dakota", "iowa", "missouri", "kansas", "colorado", "wyoming"] },
  { name: "Nevada", slug: "nevada", abbreviation: "NV", onlineAllowed: true, courtNotes: "Nevada courts accept state-approved online traffic school courses.", approvedSchoolCount: 4, averagePrice: 22.95, description: "Nevada drivers can take a state-approved online traffic school to dismiss eligible tickets.", eligibilityNotes: "Available once every 12 months. Must not be a DUI or reckless driving offense.", certificateNotes: "School submits certificate electronically to the court.", neighboringStates: ["oregon", "idaho", "utah", "arizona", "california"] },
  { name: "New Hampshire", slug: "new-hampshire", abbreviation: "NH", onlineAllowed: true, courtNotes: "New Hampshire offers an online driver attitude program for eligible drivers.", approvedSchoolCount: 2, averagePrice: 27.99, description: "New Hampshire drivers may take an approved online driver program to address eligible traffic violations.", eligibilityNotes: "Contact the New Hampshire DMV or your court for eligibility.", certificateNotes: "Submit certificate to the NH DMV.", neighboringStates: ["maine", "vermont", "massachusetts"] },
  { name: "New Jersey", slug: "new-jersey", abbreviation: "NJ", onlineAllowed: true, courtNotes: "New Jersey courts accept approved defensive driving courses for point reduction.", approvedSchoolCount: 4, averagePrice: 24.99, description: "New Jersey drivers can take an approved defensive driving course to reduce up to 2 points on their driving record.", eligibilityNotes: "Available to any NJ licensed driver. Reduces 2 points and may lower insurance.", certificateNotes: "Course provider reports completion to the NJ MVC.", neighboringStates: ["new-york", "pennsylvania", "delaware"] },
  { name: "New Mexico", slug: "new-mexico", abbreviation: "NM", onlineAllowed: true, courtNotes: "New Mexico courts accept approved online defensive driving courses.", approvedSchoolCount: 3, averagePrice: 24.99, description: "New Mexico drivers can take an approved online defensive driving course for point reduction.", eligibilityNotes: "Available once every 12 months for eligible violations.", certificateNotes: "Submit certificate to the NM MVD and the court.", neighboringStates: ["colorado", "oklahoma", "texas", "arizona", "utah"] },
  { name: "New York", slug: "new-york", abbreviation: "NY", onlineAllowed: true, courtNotes: "New York DMV-approved online courses can reduce up to 4 points on your record.", approvedSchoolCount: 5, averagePrice: 24.99, description: "New York's Point and Insurance Reduction Program (PIRP) allows drivers to take an approved online course to reduce points and get an insurance discount.", eligibilityNotes: "Available to all NY licensed drivers. Reduces up to 4 points and provides 10% insurance discount for 3 years.", certificateNotes: "Course provider reports completion directly to the NY DMV.", neighboringStates: ["vermont", "massachusetts", "connecticut", "new-jersey", "pennsylvania"] },
  { name: "North Carolina", slug: "north-carolina", abbreviation: "NC", onlineAllowed: true, courtNotes: "North Carolina courts may allow online traffic school as part of a prayer for judgment.", approvedSchoolCount: 3, averagePrice: 24.99, description: "North Carolina drivers may attend online traffic school as part of court proceedings to reduce the impact of a violation.", eligibilityNotes: "At judge's discretion. Prayer for Judgment Continued (PJC) may be an option.", certificateNotes: "Submit certificate to the court.", neighboringStates: ["virginia", "tennessee", "georgia", "south-carolina"] },
  { name: "North Dakota", slug: "north-dakota", abbreviation: "ND", onlineAllowed: true, courtNotes: "North Dakota courts may accept online defensive driving for eligible violations.", approvedSchoolCount: 2, averagePrice: 27.99, description: "North Dakota drivers may take online traffic school to address eligible traffic violations.", eligibilityNotes: "Limited availability. Contact your court for eligibility.", certificateNotes: "Submit certificate to the ND DOT and the court.", neighboringStates: ["montana", "south-dakota", "minnesota"] },
  { name: "Ohio", slug: "ohio", abbreviation: "OH", onlineAllowed: true, courtNotes: "Ohio courts may offer online traffic school as part of a plea or sentencing option.", approvedSchoolCount: 4, averagePrice: 24.99, description: "Ohio drivers can attend online traffic school through various court-accepted programs.", eligibilityNotes: "At judge's discretion. Contact the court on your citation for options.", certificateNotes: "Submit certificate to the court to fulfill your requirement.", neighboringStates: ["michigan", "indiana", "kentucky", "west-virginia", "pennsylvania"] },
  { name: "Oklahoma", slug: "oklahoma", abbreviation: "OK", onlineAllowed: true, courtNotes: "Oklahoma courts accept state-approved online defensive driving courses.", approvedSchoolCount: 3, averagePrice: 24.99, description: "Oklahoma drivers can take a state-approved online defensive driving course to potentially dismiss a traffic ticket.", eligibilityNotes: "Available once every 24 months for eligible violations.", certificateNotes: "Submit certificate to the court before your hearing date.", neighboringStates: ["kansas", "missouri", "arkansas", "texas", "new-mexico", "colorado"] },
  { name: "Oregon", slug: "oregon", abbreviation: "OR", onlineAllowed: true, courtNotes: "Oregon courts may allow online traffic school in some circuits.", approvedSchoolCount: 3, averagePrice: 25.99, description: "Oregon drivers may be eligible for online traffic school depending on their court and violation type.", eligibilityNotes: "Varies by court. Contact the court on your citation before enrolling.", certificateNotes: "Submit certificate to the court.", neighboringStates: ["washington", "idaho", "nevada", "california"] },
  { name: "Pennsylvania", slug: "pennsylvania", abbreviation: "PA", onlineAllowed: true, courtNotes: "Pennsylvania accepts approved online defensive driving courses for point reduction.", approvedSchoolCount: 4, averagePrice: 24.99, description: "Pennsylvania drivers can complete an approved defensive driving course to reduce points on their record.", eligibilityNotes: "Available to any PA licensed driver. Can reduce up to 3 points once every 12 months.", certificateNotes: "Course provider reports completion to PennDOT.", neighboringStates: ["new-york", "new-jersey", "delaware", "maryland", "west-virginia", "ohio"] },
  { name: "Rhode Island", slug: "rhode-island", abbreviation: "RI", onlineAllowed: true, courtNotes: "Rhode Island offers limited online traffic school options.", approvedSchoolCount: 2, averagePrice: 27.99, description: "Rhode Island drivers may take an approved course to address eligible traffic violations.", eligibilityNotes: "Contact the RI DMV or Traffic Tribunal for eligibility.", certificateNotes: "Submit certificate to the RI Traffic Tribunal.", neighboringStates: ["massachusetts", "connecticut"] },
  { name: "South Carolina", slug: "south-carolina", abbreviation: "SC", onlineAllowed: true, courtNotes: "South Carolina courts may accept online defensive driving at the judge's discretion.", approvedSchoolCount: 3, averagePrice: 24.99, description: "South Carolina drivers may attend online defensive driving as directed by the court.", eligibilityNotes: "At judge's discretion. Contact the court on your ticket.", certificateNotes: "Submit certificate to the court.", neighboringStates: ["north-carolina", "georgia"] },
  { name: "South Dakota", slug: "south-dakota", abbreviation: "SD", onlineAllowed: true, courtNotes: "South Dakota courts may accept online defensive driving in limited cases.", approvedSchoolCount: 2, averagePrice: 27.99, description: "South Dakota drivers may be eligible for online traffic school in limited cases.", eligibilityNotes: "Contact your court for availability.", certificateNotes: "Submit certificate to the court.", neighboringStates: ["north-dakota", "minnesota", "iowa", "nebraska", "wyoming", "montana"] },
  { name: "Tennessee", slug: "tennessee", abbreviation: "TN", onlineAllowed: true, courtNotes: "Tennessee courts accept state-approved online defensive driving courses.", approvedSchoolCount: 4, averagePrice: 24.99, description: "Tennessee drivers can take an approved online defensive driving course to dismiss eligible tickets.", eligibilityNotes: "Available once per violation. Must be approved by the court.", certificateNotes: "Submit certificate to the court before your court date.", neighboringStates: ["kentucky", "virginia", "north-carolina", "georgia", "alabama", "mississippi", "arkansas", "missouri"] },
  { name: "Texas", slug: "texas", abbreviation: "TX", onlineAllowed: true, courtNotes: "Texas has a well-established online defensive driving program. All listed courses are TDLR-approved.", approvedSchoolCount: 5, averagePrice: 19.95, description: "Texas is one of the top states for online defensive driving. TDLR-approved courses can dismiss tickets and provide insurance discounts.", eligibilityNotes: "Available once every 12 months. Must request driving safety course from the court. Speed must not exceed 25 mph over limit.", certificateNotes: "School provides certificate to submit to the court along with your driving record.", neighboringStates: ["new-mexico", "oklahoma", "arkansas", "louisiana"] },
  { name: "Utah", slug: "utah", abbreviation: "UT", onlineAllowed: true, courtNotes: "Utah courts accept approved online defensive driving for eligible violations.", approvedSchoolCount: 3, averagePrice: 24.99, description: "Utah drivers can take an approved online defensive driving course to reduce points from eligible violations.", eligibilityNotes: "Available for eligible moving violations. Contact the court for approval.", certificateNotes: "Submit certificate to the court.", neighboringStates: ["idaho", "wyoming", "colorado", "new-mexico", "arizona", "nevada"] },
  { name: "Vermont", slug: "vermont", abbreviation: "VT", onlineAllowed: true, courtNotes: "Vermont offers limited online driver improvement program options.", approvedSchoolCount: 2, averagePrice: 29.99, description: "Vermont drivers may take an approved driver improvement course to address eligible violations.", eligibilityNotes: "Contact the Vermont DMV for eligibility.", certificateNotes: "Submit certificate to the Vermont DMV.", neighboringStates: ["new-hampshire", "massachusetts", "new-york"] },
  { name: "Virginia", slug: "virginia", abbreviation: "VA", onlineAllowed: true, courtNotes: "Virginia courts accept approved online driver improvement courses.", approvedSchoolCount: 4, averagePrice: 24.99, description: "Virginia drivers can take an approved online driver improvement course to reduce demerit points.", eligibilityNotes: "Reduces up to 5 safe driving points. Available once every 24 months.", certificateNotes: "Course provider reports completion to the Virginia DMV.", neighboringStates: ["maryland", "west-virginia", "kentucky", "tennessee", "north-carolina"] },
  { name: "Washington", slug: "washington", abbreviation: "WA", onlineAllowed: true, courtNotes: "Washington courts may allow online traffic school to defer a ticket.", approvedSchoolCount: 3, averagePrice: 25.99, description: "Washington drivers can take online traffic school as part of a ticket deferral program in participating courts.", eligibilityNotes: "Deferral available once every 7 years. Court must approve.", certificateNotes: "Submit certificate to the court as part of your deferral.", neighboringStates: ["oregon", "idaho"] },
  { name: "West Virginia", slug: "west-virginia", abbreviation: "WV", onlineAllowed: true, courtNotes: "West Virginia courts may accept online defensive driving for eligible violations.", approvedSchoolCount: 2, averagePrice: 26.99, description: "West Virginia drivers may take online defensive driving to reduce the impact of eligible traffic violations.", eligibilityNotes: "Contact the court on your citation for eligibility.", certificateNotes: "Submit certificate to the court.", neighboringStates: ["ohio", "pennsylvania", "maryland", "virginia", "kentucky"] },
  { name: "Wisconsin", slug: "wisconsin", abbreviation: "WI", onlineAllowed: true, courtNotes: "Wisconsin courts may accept online traffic school in some municipalities.", approvedSchoolCount: 3, averagePrice: 25.99, description: "Wisconsin drivers may attend online traffic school as offered by participating courts.", eligibilityNotes: "Availability varies by municipality. Contact your court.", certificateNotes: "Submit certificate to the court.", neighboringStates: ["minnesota", "iowa", "illinois", "michigan"] },
  { name: "Wyoming", slug: "wyoming", abbreviation: "WY", onlineAllowed: true, courtNotes: "Wyoming courts may accept online defensive driving for eligible violations.", approvedSchoolCount: 2, averagePrice: 27.99, description: "Wyoming drivers may take online traffic school to address eligible traffic violations.", eligibilityNotes: "Limited availability. Contact the court on your citation.", certificateNotes: "Submit certificate to the court.", neighboringStates: ["montana", "south-dakota", "nebraska", "colorado", "utah", "idaho"] },
];

export function getStateBySlug(slug: string): State | undefined {
  return states.find((s) => s.slug === slug);
}

export function getAllStateSlugs(): string[] {
  return states.map((s) => s.slug);
}
